version: "3.9"

services:
  app:
    build:
      context: .
      target: production
    image: node-neon-app
    container_name: node-neon-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
